# Generated by Django 2.1.2 on 2018-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile/avatar', verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True, unique=True, verbose_name='uid'),
        ),
    ]
