# Generated by Django 2.1.2 on 2018-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20181110_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_third',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否都第三方登录'),
        ),
    ]
