# Generated by Django 2.0.8 on 2019-01-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_profile_is_third'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_third',
            field=models.BooleanField(default=False, verbose_name='是否都第三方登录'),
        ),
    ]
