# Generated by Django 2.1.2 on 2018-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goods', '0002_bidrecord_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='step_price',
            field=models.FloatField(default=1, verbose_name='每次出价价格'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='index',
            field=models.IntegerField(default=0, verbose_name='图片顺序'),
        ),
    ]
