# Generated by Django 2.1.2 on 2018-11-08 14:37

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('msg_type', models.IntegerField(choices=[(1, '竞拍消息'), (2, '拍卖公告'), (3, '系统消息')], verbose_name='消息类型')),
                ('content', markdownx.models.MarkdownxField()),
                ('periods', models.IntegerField(verbose_name='公告期数')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
        migrations.CreateModel(
            name='MsgHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否被删除')),
                (
                    'msg',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg.Msg', verbose_name='消息')),
            ],
            options={
                'verbose_name': '消息处理',
                'verbose_name_plural': '消息处理',
            },
        ),
    ]
